"""
Visualisation script for training logs.

This script reads a CSV file with columns `epoch`, `train_loss` and `val_loss`,
generated by `train.py`, and plots the learning curves using Matplotlib.  The
resulting figure is saved as a PNG file and displayed on screen if running
locally.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import matplotlib.pyplot as plt
import csv


def main() -> None:
    parser = argparse.ArgumentParser(description="Visualise training and validation loss curves")
    parser.add_argument("--logfile", type=str, required=True, help="CSV file produced by train.py")
    parser.add_argument("--output", type=str, default="loss_curve.png", help="Output image filename")
    args = parser.parse_args()

    epochs = []
    train_losses = []
    val_losses = []
    with open(args.logfile) as f:
        reader = csv.DictReader(f)
        for row in reader:
            epochs.append(int(row["epoch"]))
            train_losses.append(float(row["train_loss"]))
            val_losses.append(float(row["val_loss"]))

    plt.figure(figsize=(8, 5))
    plt.plot(epochs, train_losses, label="Train Loss")
    plt.plot(epochs, val_losses, label="Validation Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Cross‑Entropy Loss")
    plt.title("Training and Validation Loss")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(args.output)
    print(f"Saved loss curve to {args.output}")


if __name__ == "__main__":
    main()
